[package]
name = "modbot"
version = "0.1.0"
description = "Discord bot for https://mod.io"
readme = "README.md"
repository = "https://github.com/nickelc/modio-bot"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "discord"]
edition = "2018"

[dependencies]
bytesize = "1"
chrono = "0.4"
dotenv = "0.13"
env_logger = "0.6"
futures = "0.1"
log = "0.4"
reqwest = "0.9"
serenity = "0.5"
tokio = "0.1"

[dependencies.modio]
version = "0.4"

[dependencies.diesel]
version = "1.4"
features = ["r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "1.4"

[dependencies.libsqlite3-sys]
version = ">=0.8.0, <0.13.0"
optional = true
features = ["min_sqlite_version_3_7_16"]

[build-dependencies]
vergen = "3"

[features]
sqlite-bundled = ["libsqlite3-sys/bundled"]

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
