[package]
name = "modbot"
version = "0.2.0"
description = "Discord bot for https://mod.io"
readme = "README.md"
repository = "https://github.com/nickelc/modio-bot"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "discord"]
edition = "2018"

[dependencies]
bitflags = "1"
bytesize = "1"
chrono = "0.4"
dbl-rs = "0.2"
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
serenity = { version = "0.8" }
tokio = { version = "0.2", features = ["stream", "time"] }

[dependencies.modio]
git = "https://github.com/nickelc/modio-rs.git"
rev = "bc645edd"
default-features = false
features = ["rustls-tls"]

[dependencies.diesel]
version = "1.4"
features = ["r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "1.4"

[dependencies.libsqlite3-sys]
version = ">=0.8.0, <0.17.0"
optional = true
features = ["min_sqlite_version_3_7_16"]

[build-dependencies]
vergen = "3"

[features]
sqlite-bundled = ["libsqlite3-sys/bundled"]
