[package]
name = "modbot"
version = "0.1.0"
description = "Discord bot for https://mod.io"
readme = "README.md"
repository = "https://github.com/nickelc/modio-bot"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "discord"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.13"
either = "1.5"
env_logger = "0.6"
futures = "0.1"
log = "0.4"
serenity = "0.5"
tokio = "0.1"

[dependencies.modio]
version = "0.3"
git = "https://github.com/nickelc/modio-rs"

[dependencies.diesel]
version = "1.4"
features = ["r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "1.4"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
