name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - default
          - bundled
          - musl

        include:
          - build: default
            packages: libsqlite3-dev
          - build: bundled
            features: --features sqlite-bundled
          - build: musl
            features: --features sqlite-bundled
            target: x86_64-unknown-linux-musl
            packages: musl-tools

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        if: matrix.packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.packages }}

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target || 'x86_64-unknown-linux-gnu' }} ${{ matrix.features }}
